extends Node2D

signal enemy_plane_died
signal card_upgrades
signal take_damage
signal update_xp
signal increase_max_health
signal increase_damage
signal increase_attack_speed
signal reset_xp
signal coin_collected
signal load_game
signal load_skill_tree
signal update_max_hp_cost
